title: HEINER LEISKA | Photography
email: mail@leiska.de
description: >-
  Less images!

baseurl: ""
url: "https://www.leiska.de"
plugins:
  - jekyll-postcss
# Build settings
markdown: kramdown

collections_dir: collections
collections:
  projects:
    title: Projects
    output: true
    permalink: /:collection/:title/
