backend:
  name: git-gateway
  branch: master
media_folder: "/img/uploads/"
site_url: https://www.leiska.de
logo_url: https://www.leiska.de/img/logo/heinerleiska-logo.svg
collections:
  - label: "Pages"
    name: "pages"
    files:
      - name: "home"
        label: "Home"
        file: "index.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "home"}
          - {label: "Image", name: "image", widget: "image"}
          - {label: "Alternative Text", name: "alt", widget: "string"}
          - label: "Text"
            name: "text"
            widget: "object"
            fields:
              - {label: "Top", name: "top", widget: "string"}
              - {label: "Bottom", name: "bottom", widget: "string"}
      - name: "about"
        label: "About"
        file: "about/index.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "about"}
          - {label: "Image", name: "image", widget: "image"}
          - { label: 'Vita', name: 'vita', widget: 'markdown' }
          - { label: 'About', name: 'text', widget: 'markdown' }
      - name: "photography"
        label: "Photography"
        file: "photography/index.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "project-list"}
          - label: "Projects"
            name: "projects"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Thumbnail", name: "thumbnail", widget: "image"}
  - name: "architecture" 
    label: "Architecture" 
    folder: "collections/_architecture" 
    create: true 
    slug: "{{fields.slug}}"
    fields: 
      - {label: "Layout", name: "layout", widget: "hidden", default: "project-detail"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Position", name: "date", widget: "date"}
      - {label: "Photo", name: "image", widget: "image"}
      - {label: "Year", name: "year", widget: "string"}
      - {label: "Archive ID", name: "archive_id", widget: "string", required: false}
      - {label: "Description", name: "description", widget: "text", required: false}
  - name: "cake" 
    label: "Cake" 
    folder: "collections/_cake" 
    create: true 
    slug: "{{fields.slug}}"
    fields: 
      - {label: "Layout", name: "layout", widget: "hidden", default: "project-detail"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Position", name: "date", widget: "date"}
      - {label: "Photo", name: "image", widget: "image"}
      - {label: "Year", name: "year", widget: "string"}
      - {label: "Archive ID", name: "archive_id", widget: "string", required: false}
      - {label: "Description", name: "description", widget: "text", required: false}
  - name: "horizon" 
    label: "Horizon" 
    folder: "collections/_horizon" 
    create: true 
    slug: "{{fields.slug}}"
    fields: 
      - {label: "Layout", name: "layout", widget: "hidden", default: "project-detail"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Position", name: "date", widget: "date"}
      - {label: "Photo", name: "image", widget: "image"}
      - {label: "Year", name: "year", widget: "string"}
      - {label: "Archive ID", name: "archive_id", widget: "string", required: false}
      - {label: "Description", name: "description", widget: "text", required: false}
  - name: "model" 
    label: "Model" 
    folder: "collections/_model" 
    create: true 
    slug: "{{fields.slug}}"
    fields: 
      - {label: "Layout", name: "layout", widget: "hidden", default: "project-detail"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Position", name: "date", widget: "date"}
      - {label: "Photo", name: "image", widget: "image"}
      - {label: "Year", name: "year", widget: "string"}
      - {label: "Archive ID", name: "archive_id", widget: "string", required: false}
      - {label: "Description", name: "description", widget: "text", required: false}
  - name: "sand" 
    label: "Sand" 
    folder: "collections/_sand" 
    create: true 
    slug: "{{fields.slug}}"
    fields: 
      - {label: "Layout", name: "layout", widget: "hidden", default: "project-detail"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Position", name: "date", widget: "date"}
      - {label: "Photo", name: "image", widget: "image"}
      - {label: "Year", name: "year", widget: "string"}
      - {label: "Archive ID", name: "archive_id", widget: "string", required: false}
      - {label: "Description", name: "description", widget: "text", required: false}
  - name: "ship" 
    label: "Ship" 
    folder: "collections/_ship" 
    create: true 
    slug: "{{fields.slug}}"
    fields: 
      - {label: "Layout", name: "layout", widget: "hidden", default: "project-detail"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Position", name: "date", widget: "date"}
      - {label: "Photo", name: "image", widget: "image"}
      - {label: "Year", name: "year", widget: "string"}
      - {label: "Archive ID", name: "archive_id", widget: "string", required: false}
      - {label: "Description", name: "description", widget: "text", required: false}
  - name: "books" 
    label: "Books" 
    folder: "collections/_books" 
    create: true 
    slug: "{{fields.slug}}"
    fields: 
      - {label: "Layout", name: "layout", widget: "hidden", default: "book-detail"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Thumbnail", name: "thumbnail", widget: "image"}
      - label: "Images"
        name: "images"
        widget: "list"
        field: {label: "Image", name: "image", widget: "image"}
      - label: "Deutsch"
        name: "de"
        widget: "object"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Cover", name: "cover", widget: "string"}
          - {label: "Pages", name: "pages", widget: "string"}
          - {label: "languages", name: "languages", widget: "string"}
          - {label: "dimensions", name: "dimensions", widget: "string"}
          - {label: "publisher", name: "publisher", widget: "string"}
          - {label: "edition", name: "edition", widget: "string"}
          - {label: "isbn", name: "isbn", widget: "string"}
          - {label: "price", name: "price", widget: "number"}
      - { label: 'Text', name: 'body', widget: 'markdown' }
