backend:
  name: git-gateway
  branch: redesign
media_folder: "/img/uploads/"
site_url: https://www.leiska.de
logo_url: https://www.leiska.de/img/logo/heinerleiska-logo.svg
collections:
  - label: "Pages"
    name: "pages"
    files:
      - name: "home"
        label: "Home"
        file: "index.md"
        fields:
          - { label: "Layout", name: "layout", widget: "hidden", default: "home" }
          - { label: 'Text', name: 'body', widget: 'markdown' }
      - name: "about"
        label: "About"
        file: "about/index.md"
        fields:
          - { label: "Layout", name: "layout", widget: "hidden", default: "about" }
          - { label: 'Text', name: 'body', widget: 'markdown' }
  - name: "projects"
    label: "Projects"
    folder: "collections/_projects"
    create: true
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "project" }
      - { label: "Series", name: "series", widget: "string" }
      - label: 'Images'
        name: 'images'
        widget: 'list'
        fields:
          - { label: "Image", name: "image", widget: "image" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: 'Information', name: 'info', widget: 'markdown' }
